services:
  reolink-timeline-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reolink-timeline-viewer
    env_file:
      - .env
    ports:
      - "8085:8085"
    volumes:
      - /volume1/homes/ftp_reolink:/data/reolink:ro
    restart: unless-stopped
